### ISSUE TITLE
Create Document Detailing NERC/ESI Plans

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#177] opened 2021-12-15 17:06 UTC
This document should address immediate NERC concerns, as well as speculate about future directions of interest to NERC.

**Comment by tzumainn** [comment] 2021-12-17 19:11
https://docs.google.com/document/d/1L29m9krGx2zlCAEiwtKxBc6_cybDaVSMC5b18Jw73gA/edit#

**Comment by joachimweyl** [comment] 2023-10-24 17:30
@gagansk is this a duplicate of https://github.com/CCI-MOC/esi/issues/348

**Comment by joachimweyl** [comment] 2024-05-22 15:06
closing as dup of https://github.com/CCI-MOC/esi/issues/348

**Closed by joachimweyl** 2024-05-22 15:06 UTC
Labels: documentation, duplicate, generateMoreTasks
