### ISSUE TITLE
Investigate and implement using Ironic to programatically send allowlist and excludelist to Keylime verifier

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#57] opened 2021-05-27 20:52 UTC
This is slightly trickier than it should be as Keylime is not in PYPI and does not have an api for doing this. There is only the keylime tenant cli and the keylime webapp. The webapp is likely the solution we need

**Comment by tzumainn** [comment] 2021-05-27 20:53
Is this still needed, or is it a workflow that we won't handle for now? If the latter, add a comment to https://github.com/CCI-MOC/esi/issues/40 so we remember to document the gap.

**Comment by DanNiESh** [comment] 2021-07-09 14:18
We've found the cause of the agent's connection refused error: the agent can't handle requests simultaneously. The tenant call happens during the agent registration and thus it couldn't get a response. One workaround is when ironic receives keylime info from ipa, it makes calls to registrar to get the status of the agent. Once the agent is activated, it then commands the tenant call.

**Comment by ljmcgann** [comment] 2021-07-09 14:43
There were also a few Keylime bugs discovered along the way. One is that there are no registrar flags in the tenant so the tenant was trying to reach a registrar in the controller's Keylime CONF file. Modifying the CONF file works, but this bug also limits non-admins from being able to bring their own Keylime instance in as they wouldn't have access to this file.

Another bug we encountered had to do with Keylime not flushing certificates correctly. We don't currently understand how this might affect a deployed instance, but for now we have gotten around it by changing the check_ek_cert flag to False in the CONF file.

**Comment by tzumainn** [comment] 2021-07-09 14:48
Nice finds! I assume you're going to have workarounds for these issues; can you create new cards to track the bugs, so that once they're fixed the workarounds can be removed?

**Comment by gagansk** [comment] 2021-07-19 14:49
@ljmcgann and @DanNiESh Please create a task for submitting the code and close this issue.

**Closed** 2021-07-19 16:11 UTC
Labels: enhancement, standup
