### ISSUE TITLE
"No api version was specified..."

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/esi#476] opened 2023-10-13 18:26 UTC
Running `openstack esi node network list` fails with:

> No API version was specified or the requested operation was not
> supported by the client's negotiated API version 1.72.  Supported
> version range is: 1.1 to 1.72

We can work around this by setting `OS_BAREMETAL_API_VERSION=1.72` in the environment, but:

- We should be able set `baremetal_api_version` in `clouds.yaml`, but this doesn't appear to work.
- The error message suggests that the client negotiated version 1.72 and that failed, which doesn't make any sense.
- This only impacts the `openstack esi  ...` command; `openstack baremetal` commands work without error.

E.g.:

```
$ openstack baremetal node list
+--------------------------------------+-------------------+--------------------------------------+-------------+--------------------+-------------+
| UUID                                 | Name              | Instance UUID                        | Power State | Provisioning State | Maintenance |
+--------------------------------------+-------------------+--------------------------------------+-------------+--------------------+-------------+
| 6896ce51-f288-41c9-a326-f34289605878 | MOC-R4PAC21U11-S1 | 9ddfd18d-37c0-4517-9d67-f10edaadd95c | power on    | active             | False       |
| 5a48df0e-af5c-458a-9657-587d253d6c56 | MOC-R4PAC21U29-S1 | None                                 | power off   | available          | False       |
+--------------------------------------+-------------------+--------------------------------------+-------------+--------------------+-------------+
$ openstack baremetal port list
+--------------------------------------+-------------------+
| UUID                                 | Address           |
+--------------------------------------+-------------------+
| c38a407b-c8e3-412e-bb27-88d1f7fe7b41 | 0c:42:a1:51:3d:c4 |
| f6b542ca-1f10-4c5b-a562-30775ec42036 | 0c:42:a1:51:3d:c5 |
| 966de04b-0287-4d4f-abce-f70183c1d46f | 0c:42:a1:5f:7b:ac |
| 134d3f39-bf56-4dec-8497-8ad20f7eb105 | 0c:42:a1:5f:7b:ad |
+--------------------------------------+-------------------+
$ openstack esi node network list
No API version was specified or the requested operation was not
supported by the client's negotiated API version 1.72.  Supported
version range is: 1.1 to 1.72
```

**Comment by tzumainn** [comment] 2024-07-16 16:29
Closing as duplicate of https://github.com/CCI-MOC/esi/issues/555

**Closed by tzumainn** 2024-07-16 16:29 UTC
