### ISSUE TITLE
Test GPU on ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#449] opened 2023-08-01 14:58 UTC
Gagan to get additional details.

**Comment by joachimweyl** [comment] 2023-10-24 17:20
@gagansk what is the priority on this issue?

**Comment by joachimweyl** [comment] 2024-04-26 19:32
@tzumainn is this a duplicate of #520?

**Comment by tzumainn** [comment] 2024-04-26 19:45
Yep - I believe it can be closed.

**Closed** 2024-04-26 19:46 UTC
Labels: duplicate
